### ISSUE TITLE
Move to CMake broke build

### ISSUE THREAD

**Issue by flanglet** [michaelmaniscalco/msufsort#3]
Missing targets RUNTIME and ARCHIVE in INSTALL section.

Then (g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0)
[ 25%] Building CXX object CMakeFiles/msufsort.dir/src/library/msufsort/msufsort.cpp.o
/tmp/msufsort/src/library/msufsort/msufsort.cpp:488:6: error: prototype for ‘int32_t* maniscalco::msufsort::multikey_quicksort(int32_t*, int32_t*, std::size_t, maniscalco::msufsort::suffix_value, std::array<unsigned int, 2>, std::vector<maniscalco::msufsort::tandem_repeat_info>&)’ does not match any in class ‘maniscalco::msufsort’
 auto maniscalco::msufsort::multikey_quicksort
      ^~~~~~~~~~
In file included from /tmp/msufsort/src/library/msufsort/msufsort.cpp:28:0:
/tmp/msufsort/src/library/msufsort/./msufsort.h:217:24: error: candidate is: maniscalco::msufsort::suffix_index* maniscalco::msufsort::multikey_quicksort(maniscalco::msufsort::suffix_index*, maniscalco::msufsort::suffix_index*, int32_t, maniscalco::msufsort::suffix_value, std::array<unsigned int, 2>, std::vector<maniscalco::msufsort::tandem_repeat_info>&)
         suffix_index * multikey_quicksort
                        ^~~~~~~~~~~~~~~~~~
/tmp/msufsort/src/library/msufsort/msufsort.cpp:495:5: error: ‘using suffix_value = uint32_t’ is private within this context
     suffix_value startingPattern,
     ^~~~~~~~~~~~
In file included from /tmp/msufsort/src/library/msufsort/msufsort.cpp:28:0:
/tmp/msufsort/src/library/msufsort/./msufsort.h:80:43: note: declared private here
         using suffix_value = std::uint32_t;
                                           ^
/tmp/msufsort/src/library/msufsort/msufsort.cpp:497:10: error: ‘struct maniscalco::msufsort::tandem_repeat_inf ’ is private within this context
     std::vector<tandem_repeat_info> & tandemRepeatStack
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/msufsort/src/library/msufsort/msufsort.cpp:28:0:
/tmp/msufsort/src/library/msufsort/./msufsort.h:104:16: note: declared private here
         struct tandem_repeat_info
                ^~~~~~~~~~~~~~~~~~
CMakeFiles/msufsort.dir/build.make:62: recipe for target 'CMakeFiles/msufsort.dir/src/library/msufsort/msufsort.cpp.o' failed

I also cannot see where stack_frame is declared.

**Comment by michaelmaniscalco** [comment]
Gah!  First I neglected to commit the changes in `msufsort.h` and then I forgot to actually push the commit that had the changes as well!  Sorry.  It should be good now.
